### ISSUE TITLE
initial in the setting.py

### ISSUE THREAD

**Issue by shitone** [jarekwg/django-apscheduler#22]
I have seen your example, your job is very useful and good.  I found that you have to import example_apscheduler.jobs in urls.py, but it seems to be not aesthetical, how could I initial and start the `example_apscheduler.jobs.py` or  `scheduler = BackgroundScheduler()` in the setting.py.

**Comment by sallyruthstruik** [comment]
Hello @shitone. 

You can make import of jobs file in any part of your application. But if you do it in settings.py you may face with such logs:
```
  File "/home/skaledin/envs/django_apscheduler/local/lib/python2.7/site-packages/django/db/models/options.py", line 681, in _populate_directed_relation_graph
    all_models = self.apps.get_models(include_auto_created=True)
  File "/home/skaledin/envs/django_apscheduler/local/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/home/skaledin/envs/django_apscheduler/local/lib/python2.7/site-packages/django/apps/registry.py", line 168, in get_models
    self.check_models_ready()
  File "/home/skaledin/envs/django_apscheduler/local/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
AppRegistryNotReady: Models aren't loaded yet.
```

It isn't a problem, it just mean than apscheduler started working before django loads the apps. Next cycle of apscheduler will be without errors.

So feel free to import jobs file in any part of you application. I choosed urls.py because I sure that in that place of code django has been definetely initiated.

For example, I changed example in separate branch a little, try to run and check: https://github.com/jarekwg/django-apscheduler/tree/example_in_settings/examples/example_apscheduler


Also be careful, if you run your application under gunicorn/uwsgi on other multiprocessing server it means that each worker will start its own copy of BackgroundScheduler, and it may cause problems. 

In my opinion, the proper way to run scheduler is using separate script/Django command and use BlockingScheduler in it.
