### ISSUE TITLE
Why it is not using the latest  apscheduler?

### ISSUE THREAD

**Issue by joseph-vedadi** [jarekwg/django-apscheduler#51]
what is this requirement?
-e git+git@github.com:sallyruthstruik/django-apscheduler.git@9cb356e03c84850734eacadea946ccc6d24c69d2#egg=django_apscheduler

I do not fully get what the line in requremnts_dev.txt trying to do

**Comment by joseph-vedadi** [comment]
same as : 
-e git+https://github.com/jarekwg/apscheduler.git@e2f780ceffd86bce0c6732d861e73eb86a68a0e6#egg=apscheduler in requrements.txt

**Comment by jarekwg** [comment]
Ah, old relics!

The former is there because sallyruthstruik worked on their own fork for a while, so couldn't point to this package as their work wasn't published (or something to that extent).
The latter is there because we were waiting on a PR go get merged (which now is).

Happy to accept a PR that updates these.

**Comment by jcass77** [comment]
The pinned dependency has been removed in HEAD and we are back to APScheduler>=3.2.
